In [1]:
#import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
#load dataset 
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

In [3]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [4]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,18-04-2008,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,19-04-2008,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,19-04-2008,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,20-04-2008,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,20-04-2008,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [5]:
#Prepare Ball-by-Ball Data (We now create match progress features) 
# merge datasets
data = deliveries.merge(matches[['id','venue']], left_on='match_id', right_on='id')

# only first innings
data = data[data['inning'] == 1]

In [6]:
#Create Over Number 
data['over'] = data['over'].astype(int)

In [7]:
#Calculate Current Score 
data['current_score'] = data.groupby('match_id')['total_runs'].cumsum()

In [8]:
#Wickets Fallen 
data['wicket'] = data['player_dismissed'].notnull().astype(int)
data['wickets'] = data.groupby('match_id')['wicket'].cumsum()

In [9]:
#Runs in Last 5 Overs 
data['runs_last_5'] = (
    data.groupby('match_id')['total_runs']
    .rolling(window=30, min_periods=1)
    .sum()
    .reset_index(0,drop=True)
)

In [10]:
#Wickets in Last 5 Overs 
data['wickets_last_5'] = (
    data.groupby('match_id')['wicket']
    .rolling(window=30, min_periods=1)
    .sum()
    .reset_index(0,drop=True)
)

In [11]:
#Final Match Score (Target) 
final_score = data.groupby('match_id')['total_runs'].sum().reset_index()
final_score.rename(columns={'total_runs':'final_score'}, inplace=True)

data = data.merge(final_score, on='match_id')

In [12]:
#Select Our 5 Features 
model_df = data[['over','current_score','wickets','runs_last_5','wickets_last_5','final_score']]
model_df.dropna(inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19184\773028553.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  model_df.dropna(inplace=True)

In [13]:
#Train Model 
X = model_df[['over','current_score','wickets','runs_last_5','wickets_last_5']]
y = model_df['final_score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [14]:
#Evaluate
y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 14.700049564594494
R2 Score: 0.5446294913049632

In [15]:
#Save Model 
import pickle

pickle.dump(model, open("live_model.pkl", "wb"))
print("Model Saved!")

Model Saved!